/** Builds the service worker's source text with the precache version and file list baked
 *  in at build time. sw.js must change byte-for-byte on every deploy that changes the
 *  asset list (or nothing changes at all) -- a service worker whose bytes are identical to
 *  the one already installed is never considered "new" by the browser, so it would never
 *  be re-installed, never trigger an update prompt, and never clean up an old cache. This
 *  is a pure string builder (no fs/vite imports) so it is unit-testable on its own. */
export function buildServiceWorker(version: string, files: string[]): string {
  return `// Generated by the build (precache-manifest plugin in vite.config.ts). Do not edit by hand.
//
// The app shell only. Data never passes through here: Supabase is another origin, and the
// device's own cache of prices and balances lives in IndexedDB (src/offline).
//
// Navigations are network-first with a cached index.html fallback, not cache-first: GitHub
// Pages serves fresh (no-cache) HTML, and a cached page could point at hashed assets a
// newer deploy removed. Network-first with the fallback gives the same offline result
// without that failure mode.
const VERSION = ${JSON.stringify(version)};
const FILES = ${JSON.stringify(files)};
const CACHE = "shell-" + VERSION;
const SCOPE = self.registration.scope;

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)));
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith("shell-") && k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener("message", (e) => { if (e.data === "skip-waiting") self.skipWaiting(); });

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET" || !req.url.startsWith(SCOPE)) return;
  if (req.mode === "navigate") {
    e.respondWith(
      fetch(req).catch(async () => {
        const cache = await caches.open(CACHE);
        return (await cache.match(SCOPE + "index.html")) ?? Response.error();
      }),
    );
    return;
  }
  if (new URL(req.url).pathname.includes("/assets/")) {
    e.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const hit = await cache.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      await cache.put(req, res.clone());
      return res;
    })());
  }
});
`;
}
